[theme]
base="dark"
primaryColor="#1abc9c"  # Teal (accent color)
backgroundColor="#000000"  # Pure black background
secondaryBackgroundColor="#1e1e1e"  # Dark gray cards/sidebar
textColor="#ffffff"  # White text
font="sans serif"  # Optional: "serif", "monospace"

[server]
runOnSave = false
